[package]
name = "teslatte"
version = "0.0.1"
description = "A Rust crate for querying the Tesla API."
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["cli", "fancy"]

fancy = ["miette/fancy"]
cli = ["dep:clap", "dep:tracing-subscriber"]

[dependencies]
miette = { version = "5.1", features = ["fancy"] }
thiserror = "1.0.31"
tokio = { version = "1.20", features = ["full"] }
tracing = "0.1"
reqwest = { version = "0.11", features = ["rustls-tls", "cookies", "json"] }
url = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustls = "0.20"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
strum = { version = "0.24.1", features = ["derive"] }
urlencoding = "2.1.0"
derive_more = "0.99"
pkce = "0.2.0"

clap = { version = "3.2", features = ["derive", "env"], optional = true }
tracing-subscriber = { version = "0.3.17", optional = true }

[dev-dependencies]
test-log = { version = "0.2.12", default-features = false, features = ["trace"] }
