[package]
name = "teslatte"
version = "0.0.1"
description = "A Rust crate for querying the Tesla API."
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "teslatte"
path = "src/lib.rs"

[dependencies]
miette = { version = "5.1", features = ["fancy"] }
thiserror = "1.0.31"
tokio = { version = "1.20", features = ["full"] }
tracing = "0.1"
reqwest = { version = "0.11", features = ["rustls-tls", "cookies", "json"] }
url = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustls = "0.20"
sha256 = "1.0"
base64 = "0.13"
rand = "0.8"
regex = "1.5"
strum = { version = "0.24.1", features = ["derive"] }

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-subscriber = "0.3"
clap = { version = "3.2", features = ["derive", "env"]}
